version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb

  pg:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "root"
      POSTGRES_HOST_AUTH_METHOD: "trust"
